version: 1
accept_configuration:
  condition: property
  property: host.os
  equals_property: target.os

build_instructions:
  - !include "{{qt/qtbase}}/prepare_building_env.yaml"
  - !include "{{qt/qtbase}}/cmake_module_build_instructions.yaml"

test_instructions:
  - type: EnvironmentVariable
    variableName: Dummy
    variableValue: dummy
